micronaut:
  application:
    name: ${APPLICATION_NAME}
  server:
    port: ${PORT:8080}
    cors:
      enabled: true
  io:
    watch:
      paths: src/main
      restart:
  security:
    enabled: true
    authentication: bearer
    endpoints:
      writer:
        header:
          enabled: true
      propagation:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET:Indicium-Development-JWT-Secret}

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: never

jackson:
  serialization-inclusion: non_null

mongodb:
  uri: ${MONGO_URI}
  database: ${MONGO_DATABASE}