name: Gradle Publish

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/gradle-build.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
